packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  msgpackr-extract: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.5'
  - '@turbo/darwin-arm64@2.11.5'
  - '@turbo/linux-64@2.11.5'
  - '@turbo/linux-arm64@2.11.5'
  - '@turbo/windows-64@2.11.5'
  - '@turbo/windows-arm64@2.11.5'
  - turbo@2.11.5
