/** Bundled colour logos (cryptocurrency-icons v0.18.1, CC0) for common tickers; generated from assets/crypto. */
 
const LOGOS: Record<string, number> = {
  aave: require("../../assets/crypto/aave.svg"),
  ada: require("../../assets/crypto/ada.svg"),
  algo: require("../../assets/crypto/algo.svg"),
  ape: require("../../assets/crypto/ape.svg"),
  atom: require("../../assets/crypto/atom.svg"),
  avax: require("../../assets/crypto/avax.svg"),
  bat: require("../../assets/crypto/bat.svg"),
  bch: require("../../assets/crypto/bch.svg"),
  bnb: require("../../assets/crypto/bnb.svg"),
  btc: require("../../assets/crypto/btc.svg"),
  chz: require("../../assets/crypto/chz.svg"),
  comp: require("../../assets/crypto/comp.svg"),
  crv: require("../../assets/crypto/crv.svg"),
  dai: require("../../assets/crypto/dai.svg"),
  doge: require("../../assets/crypto/doge.svg"),
  dot: require("../../assets/crypto/dot.svg"),
  enj: require("../../assets/crypto/enj.svg"),
  etc: require("../../assets/crypto/etc.svg"),
  eth: require("../../assets/crypto/eth.svg"),
  fil: require("../../assets/crypto/fil.svg"),
  grt: require("../../assets/crypto/grt.svg"),
  icp: require("../../assets/crypto/icp.svg"),
  link: require("../../assets/crypto/link.svg"),
  ltc: require("../../assets/crypto/ltc.svg"),
  mana: require("../../assets/crypto/mana.svg"),
  matic: require("../../assets/crypto/matic.svg"),
  mkr: require("../../assets/crypto/mkr.svg"),
  sand: require("../../assets/crypto/sand.svg"),
  snx: require("../../assets/crypto/snx.svg"),
  sol: require("../../assets/crypto/sol.svg"),
  sushi: require("../../assets/crypto/sushi.svg"),
  trx: require("../../assets/crypto/trx.svg"),
  uni: require("../../assets/crypto/uni.svg"),
  usdc: require("../../assets/crypto/usdc.svg"),
  usdt: require("../../assets/crypto/usdt.svg"),
  wbtc: require("../../assets/crypto/wbtc.svg"),
  xlm: require("../../assets/crypto/xlm.svg"),
  xmr: require("../../assets/crypto/xmr.svg"),
  xrp: require("../../assets/crypto/xrp.svg"),
  yfi: require("../../assets/crypto/yfi.svg"),
  zrx: require("../../assets/crypto/zrx.svg"),
};

/** The bundled logo for a ticker, or null. A logo uploaded to the registry takes precedence. */
export const cryptoLogo = (symbol: string): number | null => LOGOS[symbol.toLowerCase()] ?? null;
