import { z } from "zod";

export const ERROR_CODES = [
  "VALIDATION_FAILED", "UNSUPPORTED_CHAIN", "CHALLENGE_NOT_FOUND", "CHALLENGE_EXPIRED",
  "CHALLENGE_CONSUMED", "CHALLENGE_IN_PROGRESS", "SIGNATURE_INVALID", "VERIFIER_UNAVAILABLE",
  "ADDRESS_DISABLED", "ADDRESS_ALREADY_LINKED", "CHAIN_FAMILY_ALREADY_LINKED", "SESSION_EXPIRED",
  "USER_NOT_ACTIVE", "CSRF_REJECTED", "NOT_FOUND", "OTP_INVALID", "OTP_EXPIRED",
  "OTP_ATTEMPTS_EXCEEDED", "OTP_COOLDOWN", "OTP_DELIVERY_FAILED", "RATE_LIMITED", "INVALID_TRANSITION", "APPLICATION_EXISTS",
  "APPLICATION_TOKEN_INVALID", "REPLY_NOT_ALLOWED", "FORBIDDEN", "ORGANIZATION_EXISTS", "REQUIREMENTS_INCOMPLETE", "DOCUMENT_REJECTED", "INVITE_EXISTS", "DEPLOYMENT_EXISTS", "BASKET_VALIDATION_FAILED", "VERSION_CONFLICT", "HANDLE_TAKEN",
  "NOT_INVESTABLE", "NOT_ELIGIBLE", "OPERATION_IN_PROGRESS", "QUOTE_EXPIRED", "TX_MISMATCH", "PSBT_MISMATCH", "GAS_BUDGET_EXHAUSTED", "ROUTE_UNAVAILABLE", "BTC_ADDRESS_REQUIRED", "INSUFFICIENT_BALANCE", "PRICE_MOVED", "BROADCAST_REJECTED", "DATA_STALE", "REPAIR_REQUIRED", "SHORTFALL_CHANGED", "VERSION_NOT_CURRENT", "SOL_REQUIRED", "INTERNAL",
] as const;

export const errorCodeSchema = z.enum(ERROR_CODES);
export type ErrorCode = z.infer<typeof errorCodeSchema>;

export const ERROR_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
  VALIDATION_FAILED: 400,
  UNSUPPORTED_CHAIN: 400,
  CHALLENGE_NOT_FOUND: 404,
  CHALLENGE_EXPIRED: 410,
  CHALLENGE_CONSUMED: 409,
  CHALLENGE_IN_PROGRESS: 409,
  SIGNATURE_INVALID: 401,
  VERIFIER_UNAVAILABLE: 503,
  ADDRESS_DISABLED: 403,
  ADDRESS_ALREADY_LINKED: 409,
  CHAIN_FAMILY_ALREADY_LINKED: 409,
  SESSION_EXPIRED: 401,
  USER_NOT_ACTIVE: 401,
  CSRF_REJECTED: 403,
  NOT_FOUND: 404,
  OTP_INVALID: 400,
  OTP_EXPIRED: 410,
  OTP_ATTEMPTS_EXCEEDED: 429,
  OTP_COOLDOWN: 429,
  OTP_DELIVERY_FAILED: 503,
  RATE_LIMITED: 429,
  INVALID_TRANSITION: 409,
  APPLICATION_EXISTS: 409,
  APPLICATION_TOKEN_INVALID: 401,
  REPLY_NOT_ALLOWED: 409,
  FORBIDDEN: 403,
  ORGANIZATION_EXISTS: 409,
  REQUIREMENTS_INCOMPLETE: 422,
  DOCUMENT_REJECTED: 422,
  INVITE_EXISTS: 409,
  DEPLOYMENT_EXISTS: 409,
  BASKET_VALIDATION_FAILED: 422,
  VERSION_CONFLICT: 409,
  HANDLE_TAKEN: 409,
  NOT_INVESTABLE: 409,
  NOT_ELIGIBLE: 409,
  OPERATION_IN_PROGRESS: 409,
  QUOTE_EXPIRED: 409,
  TX_MISMATCH: 409,
  PSBT_MISMATCH: 409,
  GAS_BUDGET_EXHAUSTED: 409,
  ROUTE_UNAVAILABLE: 503,
  BTC_ADDRESS_REQUIRED: 409,
  INSUFFICIENT_BALANCE: 409,
  PRICE_MOVED: 409,
  BROADCAST_REJECTED: 409,
  DATA_STALE: 409,
  REPAIR_REQUIRED: 409,
  SHORTFALL_CHANGED: 409,
  VERSION_NOT_CURRENT: 409,
  SOL_REQUIRED: 409,
  INTERNAL: 500,
};

export const apiErrorBodySchema = z.object({
  error: z.object({ code: errorCodeSchema, message: z.string(), details: z.unknown().optional() }),
});
export type ApiErrorBody = z.infer<typeof apiErrorBodySchema>;
